export default [
  "atlast.jpg",
  "group.jpg",
  "shaw.jpg",
  "making.png",
  "sitting.jpg",
  "looking.jpg",
  "staring.jpg",
  "info pic 1.jpg",
  "info pic 2.jpg",
  "info pic 3.jpg",
  "info pic 4.jpg",
  "info pic 5.jpg", 
  "info pic 7.jpg",
  "info pic 8.jpg",
  "info pic 9.jpg",
];
